# Generated by Django 2.1.5 on 2019-01-29 21:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ueditor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100, verbose_name='所属地区')),
                ('province', models.CharField(max_length=100, verbose_name='所属省')),
                ('city', models.CharField(max_length=100, verbose_name='所属城市')),
                ('longitude', models.CharField(max_length=100, verbose_name='经度')),
                ('latitude', models.CharField(max_length=100, verbose_name='纬度')),
                ('accessTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='访问时间')),
            ],
            options={
                'ordering': ('-accessTime',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', django_ueditor.models.UEditorField(blank=True, verbose_name='指令名称')),
                ('isShow', models.BooleanField(default=True, verbose_name='是否显示该条指令')),
                ('isSplit', models.BooleanField(default=True, verbose_name='是否分栏')),
                ('orderDescription', django_ueditor.models.UEditorField(blank=True, verbose_name='指令说明')),
                ('orderTypeDescription', django_ueditor.models.UEditorField(blank=True, verbose_name='指令类型说明')),
                ('number', models.IntegerField(default=1, verbose_name='排序号')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '指令',
                'verbose_name_plural': '指令列表',
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTypeName', django_ueditor.models.UEditorField(blank=True, verbose_name='指令类型名称')),
                ('number', models.IntegerField(default=1, verbose_name='排序号')),
                ('createTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '指令类型',
                'verbose_name_plural': '指令类型列表',
                'ordering': ('number',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='指令类型', to='xiaobing.OrderType'),
        ),
    ]
